name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
  - name: VERSION_MAJOR
    value: '0'
  - name: VERSION_MINOR
    value: '3'
  - group: NuGet.org

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.4.x'
  inputs:
    versionSpec: 5.4.x

- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1.x'
  inputs:
    packageType: sdk
    version: 3.1.x

- pwsh: |
    $Major=$env:VERSION_MAJOR
    $Minor=$env:VERSION_MINOR
    $Package = Find-Package -Name Blobucket -Source 'https://api.nuget.org/v3/index.json' -MinimumVersion "$($Major).$($Minor)" -MaximumVersion "$($Major).$($Minor).$([ushort]::MaxValue)" -ErrorAction SilentlyContinue
    if ($Package) {
      $Patch = [SemVer]::new($Package.Version).Patch + 1
    } else {
      $Patch = 0
    }
    $Version = "$($Major).$($Minor).$($Patch)"
    Write-Host "Version: $Version"
    Write-Host "##vso[task.setvariable variable=BUILD_VERSION;]$Version"
  displayName: Version

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: Blobucket.sln
    arguments: -c Release

- task: DotNetCoreCLI@2
  displayName: Unit Tests
  inputs:
    command: test
    arguments: '-c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'

- task: PublishCodeCoverageResults@1
  displayName: Publish Code Coverage
  inputs:
    summaryFileLocation: '**/coverage.cobertura.xml'
    codeCoverageTool: cobertura

- pwsh: |
    Get-ChildItem -Path *.nupkg -Recurse -Exclude *.symbols.nupkg | ForEach-Object {
      Write-Host "##[command]dotnet nuget push '$($_.FullName)' --source https://api.nuget.org/v3/index.json --api-key *** --skip-duplicate"
      dotnet nuget push $_.FullName --source https://api.nuget.org/v3/index.json --api-key $env:nugetApiKey --skip-duplicate
    }
  displayName: NuGet Push
  env:
    nugetApiKey: $(nuget.org-blobucket)
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')